### ISSUE TITLE
Help XPosed Safetynet

### ISSUE THREAD

**Issue by EntraptaJ** [alucas/Snorlax#27]
How can I play with the module if Pokémon go won't load? Is there a trick I'm missing?

**Comment by alucas** [comment]
Hi Kristian,

Pokémon Go does not work on rooted device by default, not because of some
Android limitation, but because Niantic doesn't whant want. Si tout need to
mais Pokémon Go think you are not root (un short : bypass safetynet). You
can look on Reddit r/pokemongodev for some technic to do so. I personally
use suhide + rootswitch

**Comment by EntraptaJ** [comment]
I am rooted and passing safetynet, but when I enable xposed it fails

**Comment by Rootkit-** [comment]
I am rooted, but when i toggle xposed with rootswitch i can launch the game nothing shows up ingame
