### ISSUE TITLE
Not showing pikachu's hat

### ISSUE THREAD

**Issue by alberturer** [alucas/Snorlax#30]
First of all, i love your module, is very useful, congrats!. In the second place, I  want to report a bug, I encountered 2 christmas pikachus but when i caught them, the hats 
disappear. I disabled the module and the hats show up. Can you check that please?

**Comment by alucas** [comment]
Hi, it's problably a proto bug, https://github.com/AeonLucid/POGOProtos is not uptodate. I will see what I can do.

**Comment by suloku** [comment]
I can confirm that disabling renaming brings back the hats. Same should apply to Raichu (yes, raichu keeps the hat).

ps: is there a way to implement ditto notification? From what I've read the client should know it's a ditto, since the colored circle depends on ditto's actual catch rate, and not the pokemon it is transformed into.

**Comment by alucas** [comment]
Please create a new ticket for the ditto question ;)
I don't really know for now.

**Comment by alucas** [comment]
Can you try that file and tell my if that fix your problem ?

[snorlax_proto_2.3.0_debug.apk.tar.gz](https://github.com/alucas/Snorlax/files/647617/snorlax_proto_2.3.0_debug.apk.tar.gz)

![screenshot_20161213-021744](https://cloud.githubusercontent.com/assets/498613/21123717/ba170fa0-c0da-11e6-8fc6-6daba838ca3f.png)

**Comment by mhetralla** [comment]
I have not tried a wild encounter, but it doesn't work in the mon list, with that apk.
![screenshot_20161213-024250](https://cloud.githubusercontent.com/assets/15217237/21124225/e5fe4f40-c0dd-11e6-9bcf-6cd68df70e05.png)

**Comment by alberturer** [comment]
I installed the debug version and i caught another santa pikachu but the issue persists. Btw, people on reddit say that the hats show up after evolving into raichu. Thanks for your effort.

**Comment by alucas** [comment]
I'm working with ElFinLazz and AeonLucid to update the proto files. I will produce a new debug apk in 1hour for you to test. Stay tuned!

**Comment by alucas** [comment]
[snorlax_proto2.3.0_debug.apk.tar.gz](https://github.com/alucas/Snorlax/files/649673/snorlax_proto2.3.0_debug.apk.tar.gz)

My USB cable just die, so I can't test anymore...

**Comment by A312a2** [comment]
Yep that works

**Comment by alberturer** [comment]
Works like a charm. Thank you so much.

**Comment by alucas** [comment]
I just released 1.7.1. I will close that Issue if everything is good ;)

**Comment by suloku** [comment]
@alucas 1.7.1 won't work for me.
As a side note, Xmas pikachu as wild encounter loaded just fine with 1.7.0 (same with 1.7.1). Maybe it's because my game is in a non-english language?

EDIT: I uninstalled and re-installed and now it works. I don't know why regular updating trough xposed module manager didn't work (I did reboot my phone after updating, and checked that snorlax was at 1.7.1 version). So it was my fault, sorry.
